### ISSUE TITLE
DeleteAsync无效

### ISSUE THREAD

**Issue by shiqingk** [Coldairarrow/EFCore.Sharding#10]
![image](https://user-images.githubusercontent.com/25786271/80858251-d9763680-8c8a-11ea-8955-26eb5379fc58.png)

最近正在学习大佬这个框架，发现异步删除不起作用，导致角色管理那里删不掉旧的菜单权限，一直在新增，旧的却没删掉

数据库是MySQL的开源版 mariadb

**Comment by Coldairarrow** [comment]
MySQL原版有这个问题吗
