### ISSUE TITLE
GetDataSetWithSql的方法移除了？

### ISSUE THREAD

**Issue by remixjc** [Coldairarrow/EFCore.Sharding#104]
GetDataSetWithSql的方法移除了？
之前这个方法有个问题为难了我很久，就是线程池数量的问题。
现在这个方法没有了，改用什么方法替换呢

**Comment by Coldairarrow** [comment]
用dapper啊，直接用SQL的话dapper更擅长

**Comment by remixjc** [comment]
好的，我研究一下。我是从您的快速框架找过来的，目前您的项目里面还没有引用dapper

**Comment by Coldairarrow** [comment]
OK
