### ISSUE TITLE
 请问有没有能跑的demo?

### ISSUE THREAD

**Issue by fayxue** [Coldairarrow/EFCore.Sharding#106]
我下载了好几个版本都运行不起来啊,尝试着修改了一些bug还是不行

**Comment by Coldairarrow** [comment]
这个注释掉，这是cicd用的
![image](https://user-images.githubusercontent.com/25943840/123389464-7c46ee00-d5cc-11eb-8db9-e6702437d7db.png)

![image](https://user-images.githubusercontent.com/25943840/123389346-5faab600-d5cc-11eb-8430-2ea234bbe4cb.png)

**Comment by Coldairarrow** [comment]
https://github.com/Coldairarrow/EFCore.Sharding/tree/master/examples/Demo.DateSharding
没问题

**Comment by fayxue** [comment]
> https://github.com/Coldairarrow/EFCore.Sharding/tree/master/examples/Demo.DateSharding
> 没问题

可以可以, 原来如此
