### ISSUE TITLE
使用sqlite时出错

### ISSUE THREAD

**Issue by chukaif** [Coldairarrow/EFCore.Sharding#121]
![image](https://user-images.githubusercontent.com/50015178/143541695-93fbbb4f-9cfb-4c37-9172-27a54bd7821f.png)
使用sqlite时出现如上错误，分析源代码后发现是 DatabaseTypeExtentions 中的SQLite连接字符串不对，少了“Data Source=”
![image](https://user-images.githubusercontent.com/50015178/143542120-5bf710d3-a17e-4dd7-9649-6c9e90621544.png)

另外 ShardingDbAccessor 中为什么不使用用户指定的连接字符串？
![image](https://user-images.githubusercontent.com/50015178/143542203-1dff13d1-cca1-4002-a2c0-223407d6df5f.png)

**Comment by Coldairarrow** [comment]
已修复
