### ISSUE TITLE
 DbContext长时间(14.087031281666667m)未释放

### ISSUE THREAD

**Issue by WangJunZzz** [Coldairarrow/EFCore.Sharding#126]
DbContext长时间(14.087031281666667m)未释放 StackTrace:   at EFCore.Sharding.GenericDbContext..ctor(DbContextOptions contextOptions, DbContextParamters paramter, EFCoreShardingOptions shardi
ngOptions)

**Comment by kevin100702** [comment]
我也出现这个问题， 我是在一个静态方法中获取service进行数据库读取后就会报这个警告信息，请问你解决这个问题了吗？

**Comment by WangJunZzz** [comment]
作者好像已经解决了

**Comment by kevin100702** [comment]
> 

更新包就可以？
