### ISSUE TITLE
动态分库分表怎么使用?

### ISSUE THREAD

**Issue by coolxiaomi** [Coldairarrow/EFCore.Sharding#25]
需求:
一个基础库里存放有租户和对应的数据库名字,
添加租户时会自动创建一个新的业务数据库,结构一样
API怎么能根据不同的租户去找到对应的数据库名字,然后连接不同业务数据库,
因为我看现在的分库方案好像是必须已知数据库名称.
谢谢!

**Comment by Coldairarrow** [comment]
框架不满足请另寻他法
