### ISSUE TITLE
System.InvalidOperationException: Cannot create a DbSet for 'Base_User' because this type is not included in the model for the context.

### ISSUE THREAD

**Issue by willhuo** [Coldairarrow/EFCore.Sharding#26]
System.InvalidOperationException: Cannot create a DbSet for 'Base_User' because this type is not included in the model for the context.

**Comment by oolanlongoo** [comment]
我昨天也遇到了，在Base_User表打[Table("base_user")]标签就好了

**Comment by willhuo** [comment]
![image](https://user-images.githubusercontent.com/15681218/83604246-712bb500-a5a8-11ea-8154-94b40f768bf4.png)


> 我昨天也遇到了，在Base_User表打[Table("base_user")]标签就好了

**Comment by willhuo** [comment]
表上有这个，还是不行

> 我昨天也遇到了，在Base_User表打[Table("base_user")]标签就好了
