### ISSUE TITLE
求DbFactory.GetRepository替代方法

### ISSUE THREAD

**Issue by wensaint** [Coldairarrow/EFCore.Sharding#45]
上一版本有以下方法：
var db = DbFactory.GetRepository(_conString, _databaseType)

--------------------------------
最新版本，DbFactory由public成了internal，请问可存在替换方法获取db

**Comment by Coldairarrow** [comment]
注入IDbFactory

**Comment by wensaint** [comment]
谢谢。再确认一下，新版通过严格测试吗，我看你自己写的Colder.Admin.AntdVue还未升级EFCore.Sharding

**Comment by Coldairarrow** [comment]
已升级
