### ISSUE TITLE
SetDateSharding 中的startTime 含义是什么？

### ISSUE THREAD

**Issue by maikebing** [Coldairarrow/EFCore.Sharding#50]
config.SetDateSharding<Base_UnitTest>(nameof(Base_UnitTest.CreateTime), ExpandByDateMode.PerMinute, startTime);

**Comment by Coldairarrow** [comment]
项目开始时间，一旦设置不再改变，应该是一个常量

**Comment by maikebing** [comment]
那小于这个时间的数据 能入库吗？

**Comment by Coldairarrow** [comment]
不行，这个时间应小于你数据的最开始时间

**Comment by maikebing** [comment]
startTime   如果我永远设置为 DateTime.Now , 实际上项目我从昨天开始的， 按日分表的， 那么 今天程序重新运行， startTime 依然是 DateTime.Now , 那么我能查昨天的数据吗？

**Comment by Coldairarrow** [comment]
不能
startTime 一旦设定就不能改了

**Comment by maikebing** [comment]
哎呦， 这怎么办？意思我配置文件里写好？有没有偷懒办法， 根据数据库 或者有什么选项， 查一下数据库， 不用二次设置这个值？
