### ISSUE TITLE
可以开放下长Sql语句监听吗

### ISSUE THREAD

**Issue by xiaohanlaila** [Coldairarrow/EFCore.Sharding#54]
请问可以将长Sql语句的监听接口公开，目前所有的Sql内容都统统写入日志很好，但是对于耗时较久的Sql定位不是很方便

**Comment by Coldairarrow** [comment]
需要用ELK解决

**Comment by xiaohanlaila** [comment]
明白了，您是说最终的日志最好还是集中通过elk分析对吧，非常感谢

**Comment by Coldairarrow** [comment]
对的，大规模场景还需要APM，一般情况ELK足够
