### ISSUE TITLE
不能用联合主键吗？

### ISSUE THREAD

**Issue by maikebing** [Coldairarrow/EFCore.Sharding#60]
不能用联合主键吗？
明明定义了 
` modelBuilder.Entity<TelemetryData>().HasKey(c => new { c.DeviceId, c.KeyName, c.DateTime });`
但没有效果。 

`An error occurred while accessing the Microsoft.Extensions.Hosting services. Continuing without the application service provider. Error: The entity type 'TelemetryData' requires a primary key to be defined. If you intended to use a keyless entity type call 'HasNoKey()'.`

**Comment by Coldairarrow** [comment]
![image](https://user-images.githubusercontent.com/25943840/93985020-161c0900-fdb7-11ea-8bfb-83df4bb134d0.png)
你这代码放哪的？不是IEntityTypeConfiguration把

**Comment by maikebing** [comment]
不是

**Comment by maikebing** [comment]
我似乎搞清楚了点。

**Comment by Coldairarrow** [comment]
![image](https://user-images.githubusercontent.com/25943840/94001382-03133400-fdcb-11ea-8ad1-6d939e90926d.png)
要类似这种用法

**Comment by maikebing** [comment]
感谢。 搞定了
