### ISSUE TITLE
关于分表字段的请教

### ISSUE THREAD

**Issue by larssonsun** [Coldairarrow/EFCore.Sharding#65]
首先感谢作者的轮子。
通过阅读项目介绍，我发现包括效率测试在内的例子在查询时都没有使用分表字段进行筛选。是否不使用分表字段进行筛选对性能影响不大？（通常分表字段都不具备实际业务价值）。

期待您的回复。

**Comment by Coldairarrow** [comment]
分表字段非常重要啊，推荐做法就是根据分表字段进行筛选（比如最常用的查最近一个月的数据）

**Comment by larssonsun** [comment]
感谢回复，谢谢。
