### ISSUE TITLE
建议增加Dataset返回类型

### ISSUE THREAD

**Issue by xxoogod** [Coldairarrow/EFCore.Sharding#68]
需要调用别人写的存储过程发现是Dataset的返回类型，目前没有相应的方法。

**Comment by ghgithub** [comment]
你这个问题解决了么？求分享解决方案

**Comment by xxoogod** [comment]
> 你这个问题解决了么？求分享解决方案

你可以看看最近的Pull requests记录 。代码提交了，作者已合并。
