### ISSUE TITLE
最新的3.1使用MySQL数据库报错

### ISSUE THREAD

**Issue by LiuDanK** [Coldairarrow/EFCore.Sharding#70]
System.TypeLoadException:“Could not load type 'EFCore.Sharding.IRepository' from assembly 'EFCore.Sharding, Version=3.1.8.1, Culture=neutral, PublicKeyToken=null'.”

装完NuGet包之后就各种报错

**Comment by Coldairarrow** [comment]
版本太老，自己看发布日志

**Comment by LiuDanK** [comment]
> 版本太老，自己看发布日志

啊这,发错位置了,我本来打算发到Colder.Admin.AntdVue这个项目下的
