### ISSUE TITLE
EFCore.Sharding是否支持在业务领域层根据不同请求动态切换数据库

### ISSUE THREAD

**Issue by hwjsun** [Coldairarrow/EFCore.Sharding#71]
大佬，internal class DbFactory 这个类是 程序集范围的共享，我的业务领域层无法访问到它的GetDbAccessor方法。。如何切不同的库呢。另外请教下，同一时间有不同用户的请求进来，可以实现不同请求，访问不同的数据库吗。

**Comment by Coldairarrow** [comment]
注入IDbFactory

**Comment by hwjsun** [comment]
感谢大佬提醒。
