### ISSUE TITLE
读写分离 读取数据延迟，怎么处理

### ISSUE THREAD

**Issue by LFDCC** [Coldairarrow/EFCore.Sharding#88]
数据库用的sqlserver
用的是主从复制方式
代码写入后 读取，读取不要，要过个几秒钟才能读取到，这种情况要怎么处理
例如删除或更新数据后 ，需要刷新列表，这个时候列表是读取的从库，可能数据还没同步过来，所以就会出现 删除/更新 后列表中的数据还是原来的

**Comment by Coldairarrow** [comment]
你用的是SQLServer的Always On把，这种情况本来就是存在的，解决方案就是在实时性比较高的场景读写都用主库，报表啥的实时性要求不高的走从库

**Comment by LFDCC** [comment]
没有使用always on 用的是复制里面的发布订阅，其实我们的从库确实也只用于报表统计的，但是我本身 比较想了解下 ，对于上面我说的这种情况一般都是怎么处理的

**Comment by Coldairarrow** [comment]
实时性比较高的场景读写都用主库
