### ISSUE TITLE
GetIShardingQueryable的tolist能否只使用最新的表查询？

### ISSUE THREAD

**Issue by xuecat** [Coldairarrow/EFCore.Sharding#92]
我有些查询是在最新的表里面进行，所以我不需要所有分出去的表都参与进来。有些查询需要分表参与进来
GetIShardingQueryable的ToListAsync能否指定过滤一些表的查询执行呢？

**Comment by wsiscool** [comment]
同问

**Comment by Coldairarrow** [comment]
按时间分表，按时间查询就行了
