### ISSUE TITLE
怎么看执行sql打印

### ISSUE THREAD

**Issue by wsiscool** [Coldairarrow/EFCore.Sharding#94]
您好，我想看生成的sql，请问有配置sql输出的地方吗

**Comment by Coldairarrow** [comment]
本来就有，demo直接运行就有

**Comment by wsiscool** [comment]
我在生产项目中引用了包，只看到打印 访问分表：xxxxxx,没有看见生成的sql，是不是我配置有问题

**Comment by Coldairarrow** [comment]
日志是基于微软自带的ILogger体系的，如果你没有注入ILogger实现，那就没有
![image](https://user-images.githubusercontent.com/25943840/114677291-bc703180-9d3c-11eb-9f75-09ae1694577d.png)

**Comment by wsiscool** [comment]
好的，谢谢
