### ISSUE TITLE
去除dapper依赖，去除GetlistBySql相关方法（有需要手写SQL直接使用dapper即可）

### ISSUE THREAD

**Issue by Coldairarrow** [Coldairarrow/EFCore.Sharding#98]

**Comment by myu123-test** [comment]
HI，After you remove the GetListBySql methods, I can't upgrade the project directly, I have to write it by hand, but how do I get some option parameters?Such as Connection timeout, transction, and so on

**Comment by myu123-test** [comment]
Can you undo those methods?Or should we write interfaces so we can rewrite them as we use them?This ensures that previous projects can be upgraded smoothly

**Comment by myu123-test** [comment]
Or you can comment out these methods in a separate file and let us, the users, refer to the package
